### ISSUE TITLE
Scylla connection picker is racy

### ISSUE THREAD

**Issue by buni** [scylladb/gocql#6]
### What version of Cassandra are you using?
Scylla 3.0.2

### What version of Gocql are you using?
latest/master

### What did you do?
Run a bunch of queries in parallel 

### What did you expect to see?
No race conditions.

### What did you see instead?
Race conditions caused by the Scylla connection picker (https://github.com/scylladb/gocql/blob/master/scylla.go), mainly the Pick() method but it looks like the whole thing is prone to race conditions.

**Comment by mmatczuk** [comment]
Please note that synchronization is taken care of by `hostConnPool`. Could you also please include the data race that you got and hash of the version you are using.

**Comment by mmatczuk** [comment]
@buni thanks for reporting. This affects range queries and all situations where token is not specified. I fixed the issue and squashed it into f702adf. The issue was that hostConnPool uses `sync.RWMutex` so we needed additional protection here. A [test](https://github.com/scylladb/gocql/blob/master/scylla_test.go#L62) was added to assure that it works.
